default_install_hook_types: [pre-commit, prepare-commit-msg]
ci:
  autofix_commit_msg: "chore: Auto update by pre-commit hooks [skip changelog]"
  autofix_prs: true
repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --config ./.pre-commit.prettierrc.cjs --write --ignore-unknown .
        language: node
        additional_dependencies:
          - prettier@3.6.2
          - "@trivago/prettier-plugin-sort-imports@5.2.2"
