name: Website Workflow

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:
    inputs:
      deploy-to-prod:
        description: "Deploy to prod"
        default: false
        required: true
        type: boolean

jobs:
  build:
    name: Build and Deploy
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          show-progress: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          # version: 10  # Already specified in package.json
          run_install: false

      - name: Setup node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: "./pnpm-lock.yaml"

      - name: Install node modules
        run: pnpm install --recursive --frozen-lockfile

      - name: Lint check
        if: ${{ inputs.deploy-to-prod != true }}
        run: |
          pnpm lint:code || {
            echo "::warning title=Lint Check::ESLint reported issues. Please fix them before deploying to production."
          }

      - name: Build
        run: pnpm run build

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: "./dist"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ inputs.deploy-to-prod == true }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./dist"
          publish_branch: gh-pages
