name: Website Workflow

on:
  push:
    branches:
      - dev
  pull_request:
  workflow_dispatch:
    inputs:
      deploy-to-prod:
        description: "Deploy to prod"
        default: false
        required: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    name: Build and Deploy
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          show-progress: false

      - uses: pnpm/setup@v1
        with:
          cache: true

      - name: Lint check (format)
        if: ${{ inputs.deploy-to-prod != true }}
        run: |
          pnpm lint:format || {
            echo "::warning title=Lint Check::Prettier reported issues. Please fix them before deploying to production."
          }

      - name: Lint check (code)
        if: ${{ inputs.deploy-to-prod != true }}
        run: |
          pnpm lint:code || {
            echo "::warning title=Lint Check::ESLint reported issues. Please fix them before deploying to production."
          }

      - name: Build
        run: pnpm run build

      - name: Upload artifact to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: "./dist"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ inputs.deploy-to-prod == true }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./dist"
          publish_branch: gh-pages
